# Generated by Django 5.1.3 on 2024-11-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, default='1', max_length=100),
        ),
    ]
