# Generated by Django 5.1.3 on 2024-11-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0003_category_post_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('berita', 'Berita'), ('turnamen', 'Turnamen'), ('bursa_transfer', 'Bursa Transfer')], default='berita', max_length=50),
        ),
    ]
