# Generated by Django 5.1.3 on 2024-11-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0004_delete_category_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('berita', 'Berita'), ('turnamen', 'Turnamen'), ('tips', 'Tips'), ('bursa_transfer', 'Bursa Transfer')], default='berita', max_length=50),
        ),
    ]
